### ISSUE TITLE
Define all the modules and the techologies to be used

### ISSUE THREAD

**Issue by pepo27** [Ambienta2MX/Ambienta2MX-Docs#3]
Consider the next image (the one that Silva checked on the last presentation):

![diagramaambienta2mx](https://cloud.githubusercontent.com/assets/3600174/7617099/afbda8b4-f96e-11e4-9887-72f70a92248f.png)

We have to define all the modules, @egjimenezg has further ideas about the technologies but we all need to check it later.

I'll define Ambienta2MX/FastEagle module because I'm working on it, I'll upload the .tex file with all the images, do we have a defined file structure?? or we're just uploading text files?

**Comment by pepo27** [comment]
I couldn't compile the Tex files X__X I'm on Ubuntu 14.04 and says that Spanish library wasn't found, maybe we could need to use the same environment to avoid that kind of problems. I was hoping a further description about the technologies to be used in each module @egjimenezg. I'll create my information in a docx file, as soon as we are on the same environment I'll pass all the information to Latex.

**Comment by egjimenezg** [comment]
@pepo27
That problem can be solved using this:

__sudo apt-get install texlive-lang-spanish__

I'm working on the document creation using ubuntu, later i will put the necessary software on the README file.

**Comment by pepo27** [comment]
Cool, Try using gummi, it's a *Tex Live editor :P n.n

**Comment by pepo27** [comment]
All the information about the project was synced with Google Drive.

**Comment by pepo27** [comment]
We're following the next Gantt Diagram, all the milestones will try to follow it. Will be synced with the other repositories.

![ganttdiagram](https://cloud.githubusercontent.com/assets/3600174/7632248/abcf2c30-fa10-11e4-9a95-5d47435f2ad3.png)
